services:
  postgres:
    image: postgres:18-alpine
    container_name: newproject_postgres
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DB_USER} #${DB_USER} #postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD} #${DB_PASSWORD} #secret
      POSTGRES_DB: ${DB_NAME} #${DB_NAME} #postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "$$POSTGRES_USER" -d postgres'] #... -d "$$POSTGRES_DB"']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - app_network


  traefik:
    image: traefik:v3.7
    container_name: newproject_traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app_network


  auth:
    build: ms_auth
    env_file:
      - ./ms_auth/.env.config
    depends_on:
      - postgres
    ports:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-router.entrypoints=web"
      - "traefik.http.routers.auth-router.rule=Host(`localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-router.service=auth-service"
      - "traefik.http.services.auth-service.loadbalancer.server.port=8000"
    networks:
      - app_network


  menu:
    build: ms_menu
    env_file:
      - ./ms_menu/.env.config
    depends_on:
      - postgres
    ports:
      - 8001
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.menu-service.loadbalancer.server.port=8001"
      - "traefik.http.routers.menu-read-router.entrypoints=web"
      - "traefik.http.routers.menu-read-router.rule=Host(`localhost`) && PathPrefix(`/menu`) && Method(`GET`)"
      - "traefik.http.routers.menu-read-router.service=menu-service"
      - "traefik.http.routers.menu-write-router.entrypoints=web"
      - "traefik.http.routers.menu-write-router.rule=Host(`localhost`) && PathPrefix(`/menu`) && (Method(`POST`) || Method(`PUT`) || Method(`PATCH`) || Method(`DELETE`))"
      - "traefik.http.routers.menu-write-router.service=menu-service"
      - "traefik.http.routers.menu-write-router.middlewares=menu-auth"
      - "traefik.http.middlewares.menu-auth.forwardauth.address=http://auth:8000/auth/validate?permission=manage_menu"
      - "traefik.http.middlewares.menu-auth.forwardauth.authRequestHeaders=Authorization"
    networks:
      - app_network


  celery-worker:
    build: ms_auth
    container_name: ms_auth_celery_worker
    entrypoint: ""
    command: python -m celery -A src.core.celery_app worker --loglevel=info
    env_file:
      - ./ms_auth/.env.config
    depends_on:
      - postgres
      - rabbitmq
      - redis
#    volumes:
#      - ./ms_auth/src:/app/src
    networks:
      - app_network


  redis:
    image: redis:8.8-alpine
    container_name: automation_redis
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app_network


  rabbitmq:
    image: rabbitmq:3.12-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=mquser
      - RABBITMQ_DEFAULT_PASS=mqpassword
      # - RABBITMQ_SERVER_ASSITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648 ( определяет порог при котором rabbitmq перестанет писать в стейт при свободном месте в 2 гб )
    ports:
      - 15672:15672
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:

#grep -n 'err'
