services:
  postgres:
    image: postgres:18-alpine
    container_name: newproject_postgres
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DB_USER} #${DB_USER} #postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD} #${DB_PASSWORD} #secret
      POSTGRES_DB: ${DB_NAME} #${DB_NAME} #postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "$$POSTGRES_USER" -d postgres'] #... -d "$$POSTGRES_DB"']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  traefik:
    image: traefik:v3.7
    container_name: newproject_traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#    networks:
#      - traefik_public

  app:
    build: ms_auth
    env_file:
      - .env.prod
    depends_on:
      - postgres
    ports:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
#    networks:
#      - traefik_public

  celery-worker:
    build: ms_auth
    container_name: ms_auth_celery_worker
    entrypoint: ""
    command: python -m celery -A src.core.celery_app worker --loglevel=info
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - rabbitmq
      - redis
    volumes:
      - ./ms_auth/src:/app/src

  redis:
    image: redis:8.8-alpine
    container_name: automation_redis
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=mquser
      - RABBITMQ_DEFAULT_PASS=mqpassword
      # - RABBITMQ_SERVER_ASSITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648 ( определяет порог при котором rabbitmq перестанет писать в стейт при свободном месте в 2 гб )
    ports:
      - 15672:15672

#networks:
#  traefik_public:
#    external: true

volumes:
  postgres_data:

#grep -n 'err'

#