"""initial_tables

Revision ID: b0b2421b6eee
Revises: 
Create Date: 2026-06-24 16:37:58.778096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b2421b6eee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('composition', sa.String(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_index(op.f('ix_menu_positions_id'), 'positions', ['id'], unique=False, schema='menu')
    op.create_table('super_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_index(op.f('ix_menu_super_positions_id'), 'super_positions', ['id'], unique=False, schema='menu')
    op.create_table('super_position_items',
    sa.Column('super_position_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['menu.positions.id'], ),
    sa.ForeignKeyConstraint(['super_position_id'], ['menu.super_positions.id'], ),
    sa.PrimaryKeyConstraint('super_position_id', 'position_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('super_position_items')
    op.drop_index(op.f('ix_menu_super_positions_id'), table_name='super_positions', schema='menu')
    op.drop_table('super_positions', schema='menu')
    op.drop_index(op.f('ix_menu_positions_id'), table_name='positions', schema='menu')
    op.drop_table('positions', schema='menu')
    # ### end Alembic commands ###
