services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.prod
    container_name: newproject_postgres
    environment:
      POSTGRES_USER: ${DB_USER} #postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD} #secret
      POSTGRES_DB: ${DB_NAME} #postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL", "pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      test: ["CMD-SHELL", 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  traefik:
    image: traefik:v3.7
    container_name: newproject_traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  postgres_data:

#grep -n 'err'